openapi: 3.0.0
info:
  version: 1.3.0
  title: Open API / OFLS / Entrance Management System
  license:
    name: MIT
servers:
  - url: http://localhost:8080/v1
paths:
  /logs/:
    get:
      summary: List all logs
      tags:
        - log
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetLogsSuccess'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseInternalError'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - Bearer: []
  /logs/monthly/{date}:
    get:
      summary: 年と月を指定してデータを取得する
      tags:
        - log
      parameters:
        - name: date
          in: path
          description: 取得したい年/月をYYYYMMの形式で指定
          required: true
          type: string
          pattern: \d{6}
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetLogsSuccess'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseInternalError'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - Bearer: []
  /logs/id/{id}:
    get:
      summary: 年と月を指定してデータを取得する
      tags:
        - log
      parameters:
        - name: id
          in: path
          description: 取得したい学生の学籍番号を指定
          required: true
          type: string
          pattern: (s|m|d)\d{7}
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetLogsSuccess'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseInternalError'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - Bearer: []
  /login:
    summary: Authentication Endpoint
    post:
      tags:
        - auth
      summary: 認証トークン(Bearer)の払い出し
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
              required:
                - id
                - password
      responses:
        '200':
          description: 成功.
        '401':
          description: 認証情報が違います.
        '500':
          description: サーバーの内部エラー
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Credentials for API
  schemas:
    ResponseGetLogsSuccess:
      type: object
      properties:
        logs:
          type: array
          items:
            $ref: '#/components/schemas/Logs'
          description: Multiple logs information
    Logs:
      type: object
      required:
        - id
        - date
        - entry_time
      properties:
        id:
          type: string
          pattern: (s|m|d)\d{7}
          example: s0000000
        date:
          type: string
          format: date
          example: 2000/00/00
        entry_time:
          type: string
          pattern: \d{2}:\d{2}:\d{2}
          example: '00:00:00'
        exit_time:
          type: string
          pattern: \d{2}:\d{2}:\d{2}
          example: '02:00:00'
        purpose:
          type: integer
          example: 0
        satisfication:
          type: integer
          example: 0
    ResponseInternalError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
